### ISSUE TITLE
Should we adjust "evangelist" to "dev experience" on website?

### ISSUE THREAD

**Issue by jerdog** [devrelcollective/devrelcollective.fun#16]
https://github.com/devrelcollective/devrelcollective.fun/blob/f81958b1ac5986abbcdbd7caef59830ff3d3e700/content/_index.md?plain=1#L6

**Comment by quintessence** [comment]
IMO I don't think so, I think DevEx falls under DevRel, not as the top level category.

**Comment by mary-grace** [comment]
I agree that DevEx != Evangelist or DevRel, but if what we're looking to change is the "Advocates - Community Managers - Evangelists" section, I understand the argument and would be ok with it.

**Comment by quintessence** [comment]
Ah ok - I would say in that case "in addition to" rather than "in place of" -> so "Advocates - Community Managers - Evangelists - Developer Experience"

**Comment by mbbroberg** [comment]
I'm pro adding rather than swapping -- Evangelist is still a common enough title and within the category of work we want to feel welcome.

(And for background: we were once called Evangelist Collective back when that was cool)

**Comment by phrawzty** [comment]
+1 for keeping "evangelist". It's literally my job title, for example, and I suspect that's very much the case for a lot of other people.

**Comment by quintessence** [comment]
It looks like we're all in alignment - is this the only change we're looking to make? If so, I can go ahead and make it.

**Comment by jerdog** [comment]
Seeing as this is a bit old, asking again if we should add `- Developer Experience` to the headline, or if we should replace `Evangelists` with it?

**Comment by RCheesley** [comment]
I think we should replace it with Developer Experience personally, as a lot of folks do understand and equate the terms nowadays. Having both adds a lot of extra text for something that I think in common understanding means the same. But I'm not strongly feeling either way, if others feel strongly it should be added that is fine too.

**Comment by jerdog** [comment]
Agreed - @phrawzty at the time you were the holdout on the "Evangelist" term. What say you now?

**Comment by jerdog** [comment]
Fixed this in [af156b3](https://github.com/devrelcollective/devrelcollective.fun/pull/22/commits/af156b3263b30dbe627d701f1e0054bd83260c19)

**Comment by jerdog** [comment]
Suggestion from Robin 
- Dev Advocacy / Technical Community Management / Dev Experience
